name: Build and push Docker image

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string  
      docker-context:
        required: false
        type: string  
        default: ""
    secrets:
      nexus-username:
        required: true
      nexus-password:
        required: true

jobs:
  build-push:
    name: Build and push
    runs-on: self-hosted
    steps:
      - id: set-up-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - id: set-up-docker-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - id: login-nexus
        name: Login to Nexus
        uses: docker/login-action@v1
        with:
          registry: private.nexus.cams7.ml
          username: ${{ secrets['nexus-username'] }}
          password: ${{ secrets['nexus-password'] }}
      
      - id: build-push
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}/${{ inputs['docker-context'] }}
          push: true
          tags: |
            private.nexus.cams7.ml/${{ inputs['image-name'] }}:${{ inputs['image-version'] }} 
            private.nexus.cams7.ml/${{ inputs['image-name'] }}:latest