name: Update Docker image on Kustomize file

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      kustomize-path:
        required: false
        type: string  
        default: ""
      git-email:
        required: false
        type: string  
        default: "action@github.com"
      git-username:
        required: false
        type: string
        default: "Deploy Action"
      git-commit-message:
        required: false
        type: string  
        default: "Update Docker image"

jobs:
  update-kustomize:
    name: Update Kustomize
    runs-on: self-hosted
    steps:
      - id: setup-kustomize
        name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: v3.6.1

      - id: update-kustomize
        name: Update Kustomize
        run: |
          cd ${{ github.workspace }}/${{ inputs['kustomize-path'] }}
          kustomize edit set image public.nexus.cams7.ml/${{ inputs['image-name'] }}=public.nexus.cams7.ml/${{ inputs['image-name'] }}:${{ inputs['image-version'] }}

      - id: commit
        name: Commit
        run: |
          git config --local user.email "${{ inputs['git-email'] }}"
          git config --local user.name "${{ inputs['git-username'] }}"
          git commit -am "${{ inputs['git-commit-message'] }}"

      - id: push
        name : Push
        uses: ad-m/github-push-action@master